### ISSUE TITLE
Project Profile Card Review and Update

### ISSUE THREAD

**Issue by akibrhast** [akibrhast/github-issue-submission-form#10]
```yaml
identification: '157484926'
title: Los Angeles Criminal Sentencing Project
description: >-
  Our project's goal is to make all criminal sentences administered in LA county
  into an open dataset. There is a lot of data about when and where crimes are
  committed - but none about what sentences are passed down in LA County.
image: /assets/images/projects/criminal-sentencing.jpg
alt: Gavel
links:
  - name: GitHub
    url: https://github.com/timdef/criminal-sentencing
location:
  - Downtown LA
  - Remote
status: Active

```

 ## [Preview Changes](#) 

 ## [Make Pull Request](#)
