### ISSUE TITLE
Project Profile Card Review and Update

### ISSUE THREAD

**Issue by akibrhast** [akibrhast/github-issue-submission-form#11]
```yaml
identification: '159286729'
title: Heart
description: >-
  Heart is a project working directly with the LA City Attorney’s Homeless
  Engagement and Response Team. The HEART program helps individuals experiencing
  homelessness resolve eligible traffic and pedestrian infractions and related
  warrants and fines by engaging with relevant services. Hack for LA is helping
  them build a database and case management system to streamline their workflow
  and enable them to scale their program.
image: /assets/images/projects/heart.png
image-hero: /assets/images/projects/heart-hero.png
alt: Programming code icon that reads helping the homeless with code.
leadership:
  - name: Marie-Aimee Brajeux
    role: Product Manager
    picture: >-
      https://user-images.githubusercontent.com/37763229/79702509-34a33480-825a-11ea-94e8-ff952f42863d.jpg
  - name: Adrian Inchauste
    role: Design Sprint Facilitator
    picture: >-
      https://user-images.githubusercontent.com/37763229/79702530-63210f80-825a-11ea-8314-93950014939d.jpg
  - name: Jason LaManque
    role: Design Sprint Facilitator
    picture: >-
      https://user-images.githubusercontent.com/37763229/79702551-9a8fbc00-825a-11ea-819f-dde8cad5d058.jpg
  - name: Lex Roman
    role: UX Advisor (1st stage)
    picture: >-
      https://avatars0.githubusercontent.com/u/1103366?s=400&u=3b85c9e08f73d0980caf99bf0e6ee005f8da925a&v=4
    links:
      github: https://github.com/calexity
  - name: Gian Reyes Dionisio
    role: UX Design Lead
    picture: https://avatars3.githubusercontent.com/u/45775543?s=400&v=4
    links:
      github: https://github.com/gianbun
  - name: Charlotte Soestini
    role: UX Design and Documentarian (post project)
    picture: https://avatars2.githubusercontent.com/u/45779646?s=400&v=4
    links:
      github: https://github.com/charlottesauce
  - name: Bonnie Wolfe
    role: Documentarian (post project)
    picture: >-
      https://avatars2.githubusercontent.com/u/37763229?s=400&u=e7cb79276f78b9fb641dac9c3540fd4301a16958&v=4
    links:
      github: https://github.com/experimentsinhonesty
  - name: Roland Abregorivas
    role: Tech Lead
    picture: >-
      https://avatars2.githubusercontent.com/u/7821047?s=400&u=9128a4d0a4d1ff33bdebae02bcdaac7ff7e7432f&v=4
    links:
      github: https://github.com/abregorivas
  - name: Tien Yuan
    role: Tech Lead
    picture: >-
      https://avatars1.githubusercontent.com/u/1626276?s=400&u=77d3408bac33631b86801cb1bcf23d172b1b9bf7&v=4
    links:
      github: https://github.com/tienyuan
links:
  - name: GitHub
    url: https://github.com/hackforla/heart
  - name: Slack
    url: https://hackforla.slack.com/messages/CDWKEBYBB
  - name: Wiki
    url: https://github.com/hackforla/heart/wiki
partner: LA City Attorney’s Homeless Engagement and Response Team
vertical: Justice
status: Active

```

 ## [Preview Changes](#) 

 ## [Make Pull Request](#)
