### ISSUE TITLE
Project Profile Card Review and Update

### ISSUE THREAD

**Issue by akibrhast** [akibrhast/github-issue-submission-form#12]
```yaml
identification: '130000551'
title: Hackforla.org Website
description: >-
  The hackforla.org website is our organization's way of communicating with
  volunteers, stakeholders, and donors. This project is a good place to start
  for new volunteers looking to polish their git protocol skills (branches,
  separation of concerns, etc.). We currently have two development paths: growth
  (building out new pages and guides) and optimization (taking inventory of our
  code and design systems) to ensure we are consistently delivering value to our
  users while being scalable in our approach to building the site.
image: /assets/images/projects/website.png
image-hero: /assets/images/projects/website-hero.jpg
alt: Wireframe sample from new website.
leadership:
  - name: Bonnie Wolfe
    role: Agile Coach/Stakeholder Rep
    picture: https://avatars.githubusercontent.com/ExperimentsInHonesty
    links:
      github: https://github.com/ExperimentsInHonesty
      slack: https://hackforla.slack.com/team/UE1UG1YFP
  - name: Kian Badie
    role: Technical Advisor
    picture: https://avatars.githubusercontent.com/KianBadie
    links:
      github: https://github.com/KianBadie
      slack: https://hackforla.slack.com/team/UNAQGKW91
  - name: Cynthia Kiser
    role: Technical Advisor
    picture: https://avatars.githubusercontent.com/cnk
    links:
      github: https://github.com/cnk
      slack: https://hackforla.slack.com/team/USBB18YDR
  - name: David Rubinstein
    role: Technical Lead
    picture: https://avatars.githubusercontent.com/drubgrubby
    links:
      github: https://github.com/drubgrubby
      slack: https://hackforla.slack.com/team/U015FP47R5G
  - name: Danielle Nedivi
    role: Design Lead
    picture: https://avatars.githubusercontent.com/daniellex0
    links:
      github: https://github.com/daniellex0
      slack: https://hackforla.slack.com/team/U013U4VN8V7
  - name: Ibraheem Agbaje
    role: Product Manager
    picture: https://avatars.githubusercontent.com/IAgbaje
    links:
      github: https://github.com/IAgbaje
      slack: https://hackforla.slack.com/team/U01FKL1DN48
  - name: Pawan Murthy
    role: Product Manager
    picture: https://avatars.githubusercontent.com/pawan92
    links:
      github: https://github.com/pawan92
      slack: https://hackforla.slack.com/team/U01FMQTN8MU
  - name: Ahdithan Uthayakumar
    role: Product Manager
    picture: https://avatars.githubusercontent.com/ahdithebomb
    links:
      github: https://github.com/ahdithebomb
      slack: https://hackforla.slack.com/team/U01FDAPULJE
  - name: Tarang Gupta
    role: Product Manager
    picture: https://avatars.githubusercontent.com/tarang100
    links:
      github: https://github.com/tarang100
      slack: https://hackforla.slack.com/team/U01FN9BAYTY
links:
  - name: Wiki
    url: https://github.com/hackforla/website/wiki
  - name: Slack
    url: https://hackforla.slack.com/archives/C4UM52W93
  - name: GitHub
    url: https://github.com/hackforla/website
  - name: Site
    url: https://www.hackforla.org
location:
  - Santa Monica
  - Downtown LA
  - Remote
looking:
  - category: UI/UX
    skill: UI (wireframes)
  - category: UI/UX
    skill: UX Researcher
  - category: Development
    skill: Junior JavaScript developers
  - category: Development
    skill: Javascript Mentor / PR reviewer
  - category: Development
    skill: >-
      anyone wanting to learn how to do Git commits in a collaborative work
      environment
technologies:
  - GitHub Pages
  - Jekyll
  - Docker
tools: Figma, Google Drive, Zoom, Google Analytics
vertical: Workforce Development
status: Active

```

 ## [Preview Changes](#) 

 ## [Make Pull Request](#)
