### ISSUE TITLE
Project Profile Card Review and Update

### ISSUE THREAD

**Issue by akibrhast** [akibrhast/github-issue-submission-form#14]
```yaml
identification: '138791772'
title: Engage
description: >-
  Engage is a civic participation platform. Currently in beta, Engage makes it
  easier for residents of Santa Monica, CA to offer their feedback on policy
  issues that City Council is considering. Engage aims to increase access for
  community stakeholders who are unable to attend public meetings or may
  otherwise feel unheard by their local government.
image: /assets/images/projects/engage.jpg
image-hero: /assets/images/projects/engage-hero.jpg
alt: City council closed in session.
leadership:
  - name: Teddy Cripeneau
    picture: https://avatars.githubusercontent.com/TeddyCr
    links:
      github: https://github.com/TeddyCr
      slack: https://hackforla.slack.com/team/UAYBYQVV3
  - name: Eli Selkin
    role: Backend Architect
    picture: https://avatars.githubusercontent.com/eselkin
    links:
      github: https://github.com/eselkin
      slack: https://hackforla.slack.com/team/U0611PL2D
links:
  - name: GitHub
    url: https://github.com/hackla-engage
  - name: Site
    url: https://sm.engage.town
  - name: Wiki
    url: https://github.com/hackla-engage/Engage-Product-Documentation/wiki
  - name: Slack
    url: https://hackforla.slack.com/archives/C6JBH478W
location:
  - Santa Monica
  - Remote
looking:
  - category: UI/UX
    skill: UX designers
  - category: Development
    skill: NLP engineers
technologies:
  - ReactJS
  - Django
  - PostgreSQL
partner: City of Santa Monica
tools: Hotjar, Google Analytics
vertical: Citizen Engagement
status: Active

```

 ## [Preview Changes](#) 

 ## [Make Pull Request](#)
