### ISSUE TITLE
Project Profile Card Review and Update

### ISSUE THREAD

**Issue by akibrhast** [akibrhast/github-issue-submission-form#15]
```yaml
                            identification: '228981080'
title: Home Unite Us
description: >-
  We're working with community non-profits who have a Host Home initiative to
  develop a workflow management tool to make the process scaleable (across all
  providers), reduce institutional bias, and effectively capture data. <br /><br
  />Host Home programs are centered around housing young people, 18 - 25 years
  old. Their approach focuses on low-cost, community-driven intervention by
  matching a willing host with a guest or group of guests, providing a stable
  housing environment for youths who are experiencing homelessness and seeking
  stable housing.
image: /assets/images/projects/home-heart.png
image-hero: /assets/images/projects/home-unite-us-hero.png
alt: Home Unite Us logo
leadership:
  - name: Tyler Thome
    role: HUU Tech Lead
    picture: https://avatars.githubusercontent.com/tylerthome
    links:
      github: https://github.com/tylerthome
      slack: https://hackforla.slack.com/team/ULN1M6UAH
  - name: Abby Hipp
    role: Product Manager
    picture: https://avatars.githubusercontent.com/abbyhipp
    links:
      github: https://github.com/abbyhipp
      slack: https://hackforla.slack.com/team/U0189RUQM7Y
  - name: Tracy Michelle
    role: Calender Tech Lead
    picture: https://avatars.githubusercontent.com/javaprincess
    links:
      github: https://github.com/javaprincess
      slack: https://hackforla.slack.com/team/U014ZPWTJV6
links:
  - name: Demo
    url: https://lacommunity.site/hosthome
  - name: GitHub
    url: https://github.com/hackforla/homeuniteus
  - name: Wiki
    url: https://github.com/hackforla/HomeUniteUs/wiki
  - name: Slack
    url: https://hackforla.slack.com/archives/CRWUG7X0C
  - name: Test site
    url: https://test.homeunite.us/
  - name: Site
    url: https://homeunite.us/
location:
  - Remote
looking:
  - category: UI/UX
    skill: UI (including wireframes, familiar with Figma)
  - category: Manager
    skill: Product Manager
  - category: Developer
    skill: React Expert
technologies:
  - ReactJS
  - NoSQL
  - Python 3
  - Flask
  - TypeScript
  - Auth0 / OIDC / OAuth2
  - MongoDB
partner: Safe Place for Youth (SPY), Point Source Youth (PSY)
tools: >-
  Figma, Miro, AWS, Nginx, Terraform, Docker, DynamoDB, Style Components, Zoom,
  GitHub, Google Drive, Docs, Sheets, Slides
vertical: Social Safety Net
status: Active

                        ```

 ## [Preview Changes](#) 

 ## [Make Pull Request](#)
