### ISSUE TITLE
Project Profile Card Review and Update

### ISSUE THREAD

**Issue by akibrhast** [akibrhast/github-issue-submission-form#18]
```yaml
identification: '276448423'
title: 100 Automations
description: >-
  Hack for LA seeks to reduce repetitive work in our open source projects and
  for the open source community.  This project will be both a showcase for the
  automations and/or microservices that we develop, but also a convenient home
  for those automations, so that they can be found, forked, and contributed to
  easily. We will be using JAMstack and a static site generator for building
  this website.
image: /assets/images/projects/100automations.png
image-hero: /assets/images/projects/100automations-hero.png
alt: >-
  100 Automations logo depicted as a 1 and two intermeshed gears surrounded by a
  open left bracket, forward slash and closing right bracket to indicate the 100
  automations are in code, followed by the word Automations.
leadership:
  - name: Niven Prasad
    role: Product Manager
    picture: https://avatars.githubusercontent.com/nivenprasad
    links:
      github: https://github.com/nivenprasad
      slack: https://hackforla.slack.com/team/U015R4RTDJA
  - name: Camila Arias
    role: UI/UX Designer
    picture: https://avatars.githubusercontent.com/CamilaArias
    links:
      github: https://github.com/CamilaArias
      slack: https://hackforla.slack.com/team/U018S4VQK3M
  - name: Olivia Chiong
    role: Product Manager
    picture: https://avatars.githubusercontent.com/Olivia-Chiong
    links:
      github: https://github.com/Olivia-Chiong
      slack: https://hackforla.slack.com/team/U01GJC7VC6L
  - name: Muhi-Dean Othman
    role: Full-Stack Developer
    picture: https://avatars.githubusercontent.com/mdothman
    links:
      github: https://github.com/mdothman
      slack: https://hackforla.slack.com/team/U01F5K8DDPW
  - name: Audrey Kim
    role: UX Writer
    picture: https://avatars.githubusercontent.com/nahyungkim1220
    links:
      github: https://github.com/nahyungkim1220
      slack: https://hackforla.slack.com/team/U01H0CXBTUM
  - name: Jason Brown
    role: UX/Product Manager
    picture: https://avatars.githubusercontent.com/superbunker
    links:
      github: https://github.com/superbunker
      slack: https://hackforla.slack.com/team/U01G7G1HMU1
links:
  - name: GitHub
    url: https://github.com/100Automations/website
  - name: Slack
    url: https://hackforla.slack.com/archives/C018S5TCQE7
  - name: Readme
    url: https://github.com/OpenSourceAutomations/OSA-Website/blob/master/README.md
  - name: Overview
    url: >-
      https://github.com/hackforla/product-management/blob/master/project-one-sheets/100-Automations-Project-One-Sheet.pdf
location:
  - Remote
looking:
  - category: Development
    skill: Anyone who wants to write open source automations
  - category: Development
    skill: API writers
  - category: Development
    skill: API integrators
  - category: Development
    skill: Frontend Javascript Developers
  - category: UI/UX
    skill: UI/UX Designer
technologies:
  - GitHub Pages
  - Jekyll
vertical: Civic Tech Infrastructure
status: Active

```

 
## [Make Pull Request](#)
