### ISSUE TITLE
Project Profile Card Review and Update

### ISSUE THREAD

**Issue by akibrhast** [akibrhast/github-issue-submission-form#25]
<details><summary>For Developer Reference</summary>

```yaml
identification: '140512203'
title: Jobs for Hope
description: >-
  We compiled job listings from 60+ different non-profit organization websites
  for the LA County Homeless Initiative and consolidated them into a single
  database so that it is easier for job-seekers to search and filter for jobs.
image: /assets/images/projects/jobs-for-hope.png
image-hero: /assets/images/projects/jobs-for-hope-hero.png
alt: LA county homelessness initiative logo.
links:
  - name: GitHub
    url: https://github.com/hackforla/jobs-for-hope
  - name: Site
    url: https://jobs-for-hope.herokuapp.com/
location:
  - Downtown LA
  - Remote
partner: LA County Homeless Initiative;
status: Active

``` 

 </details>

## [Make Pull Request](#)
