### ISSUE TITLE
Project Profile Card Review and Update

### ISSUE THREAD

**Issue by akibrhast** [akibrhast/github-issue-submission-form#28]
<details><summary>For Developer Reference</summary>

```yaml
identification: '155295655'
title: Railstats LA
description: >-
  Trailstats LA tracks LA Metro trains and generates punctuality reports. Our
  website enables both Metro officials and the public to easily review
  up-to-date statistics for LA's 6 train lines.
image: /assets/images/projects/metro-ontime.png
image-hero: /assets/images/projects/metro-ontime-hero.png
alt: metro ontime
leadership:
  - name: Cameron Sexton
    role: Product Owner/Lead Developer
    picture: https://avatars.githubusercontent.com/ctsexton
    links:
      github: https://github.com/ctsexton
      slack: https://hackforla.slack.com/team/UBENYBXGV
links:
  - name: GitHub
    url: https://github.com/metro-ontime
  - name: Site
    url: https://la.railstats.org
  - name: Readme
    url: https://github.com/metro-ontime/performance_tracker/blob/master/README.md
  - name: Slack
    url: https://hackforla.slack.com/archives/CBPK5D3BQ
  - name: LA metro
    url: https://www.metro.net/
  - name: Observable
    url: https://observablehq.com/@ctsexton/railstats-marey-diagram
location:
  - Downtown LA
  - Remote
partner: LA Metro (https://www.metro.net/)
tools: Docker, AWS, Observable
vertical: Environment
status: Active

``` 

 </details>

## [Make Pull Request](http://localhost:4000/pullRequest?MDU6SXNzdWU4MzgxODA5NDA=)
