### ISSUE TITLE
Project Profile Card Review and Update

### ISSUE THREAD

**Issue by akibrhast** [akibrhast/github-issue-submission-form#29]
<details><summary>For Developer Reference</summary>

```yaml
identification: '241519642'
title: Civic Tech Index
description: >-
  Our goal of the project is to create a comprehensive, searchable index of all
  civic tech open source software projects around the world. We have created the
  framework and an interest list. We are currently working on building out the
  website and other marketing tools that demonstrate the power of the index.
image: /assets/images/projects/civic-tech-index.png
image-hero: /assets/images/projects/civic-tech-index-hero.png
alt: >-
  Civic tech index logo layered on top of the world map. Paired with a globe
  icon and a magnifying glass.
leadership:
  - name: Bonnie Wolfe
    role: Agile Coach/Acting Technical Project Manager
    picture: https://avatars.githubusercontent.com/ExperimentsInHonesty
    links:
      github: https://github.com/ExperimentsInHonesty
      slack: https://hackforla.slack.com/team/UE1UG1YFP
  - name: Jonathan Shin
    role: Technical Mentor
    picture: https://avatars.githubusercontent.com/shinjonathan
    links:
      github: https://github.com/shinjonathan
      slack: https://hackforla.slack.com/team/U01ASHCHSP2
  - name: Olivia Chiong
    role: Product Manager
    picture: https://avatars.githubusercontent.com/Olivia-Chiong
    links:
      github: https://github.com/Olivia-Chiong
      slack: https://hackforla.slack.com/team/U01GJC7VC6L
  - name: Gio Sce
    role: Technical Product Manager
    picture: https://avatars.githubusercontent.com/giosce
    links:
      github: https://github.com/giosce
      slack: https://hackforla.slack.com/team/U01CU8059BL
  - name: Chali Prasertsri
    role: UX Lead
    picture: https://avatars.githubusercontent.com/chalimar
    links:
      github: https://github.com/chalimar
      slack: https://hackforla.slack.com/team/USLBE6X4M
  - name: Sean Flores
    role: Frontend Developer
    picture: https://avatars.githubusercontent.com/codewilling
    links:
      github: https://github.com/codewilling
      slack: https://hackforla.slack.com/team/U012CG71VD1
  - name: Bo Yang
    role: Data Analyst
    picture: https://avatars.githubusercontent.com/ddkbky
    links:
      github: https://github.com/ddkbky
      slack: https://hackforla.slack.com/team/UTW4ZPXDK
  - name: Gwendolyn Snapp
    role: Illustrator/Visual Designer
    picture: https://avatars.githubusercontent.com/GSnapp
    links:
      github: https://github.com/Gsnapp
      slack: https://hackforla.slack.com/team/UTL09G68Z
links:
  - name: GitHub
    url: https://github.com/civictechindex/website
  - name: Slack
    url: https://hackforla.slack.com/archives/CTYAKM0CW
  - name: Wiki
    url: https://github.com/civictechindex/website/wiki
  - name: Site
    url: http://civictechindex.org/
  - name: Overview
    url: >-
      https://github.com/hackforla/product-management/blob/master/project-one-sheets/Civic-Tech-Index-Product-One-Sheet.pdf
location:
  - Downtown LA
  - Remote
looking:
  - category: Development
    skill: Fullstack Developer with Node/React knowledge
  - category: Development
    skill: Front end React developers
  - category: UI/UX
    skill: UX specialist for testing and conducting interviews with stakeholders
technologies:
  - ReactJS
  - Django
  - PostgreSQL
  - ESLint
  - Code Climate
  - Cypress
partner: Code for America, Yale OpenLab and many more.
vertical: Civic Tech Infrastructure
status: Active

``` 

 </details>

## [Make Pull Request](http://localhost:4000/pullRequest?MDU6SXNzdWU4MzgxODExNjQ=)
