### ISSUE TITLE
Project Profile Card Review and Update

### ISSUE THREAD

**Issue by akibrhast** [akibrhast/github-issue-submission-form#4]
```yaml
identification: '293907049'
title: Civic Tech Structure
description: >-
  Each of the 80+ Code for America Brigades is an experiment which generates
  valuable learnings and new effective processes and practices. However,
  Brigades and other civic tech volunteer organizations need not start from
  scratch. This project aims to improve existing structures and create new ones
  that make it easier to share replicable processes and practices so that
  organizers and members can iterate on each others work, improving outcomes for
  the whole network. <br><br> The Civic Tech Structure's first project seeks to
  improve the existing Code for America Brigade Organizer’s Playbook (BOP) into
  a communal, high-value resource for sharing. We will be performing an
  intensive UX Research phase with the BOP end users to understand their
  priorities, infrastructure, and potential contributions.
image: /assets/images/projects/civic-tech-structure.png
image-hero: /assets/images/projects/civic-tech-structure-hero.png
alt: A network of lines within lines, with nodes, and a large dot in the center.
leadership:
  - name: Bonnie Wolfe
    role: Co-Product Manager
    picture: https://avatars.githubusercontent.com/ExperimentsInHonesty
    links:
      github: https://github.com/ExperimentsInHonesty
      slack: https://hackforla.slack.com/team/UE1UG1YFP
  - name: Sam H.
    role: Co-Product Manager
    picture: https://avatars.githubusercontent.com/MasSamH
    links:
      github: https://github.com/MasSamH
      slack: https://hackforla.slack.com/team/U01A2FPLBC3
  - name: Thad Kerosky
    role: Co-Product Manager
    picture: https://avatars2.githubusercontent.com/u/283343?v=4
    links:
      github: https://github.com/thadk
      slack: https://cfa.slack.com/archives/C019RCM15FE
  - name: Naomi Chao
    role: Special Projects Coordinator
    picture: https://avatars.githubusercontent.com/naomiec
    links:
      github: https://github.com/naomiec
      slack: https://hackforla.slack.com/team/U018TQWQB0T
links:
  - name: GitHub
    url: https://github.com/hackforla/civic-tech-structure
  - name: Slack
    url: https://hackforla.slack.com/archives/C01A789GTNZ
  - name: Overview
    url: >-
      https://docs.google.com/document/d/1GkvbJ9byBWBpZklYE6YL5nqa-KbIRz32PnMCeroV_1g/edit?usp=sharing
  - name: BOP Github
    url: https://github.com/codeforamerica/brigade-playbook
  - name: BOP CfA Slack
    url: https://cfa.slack.com/archives/C019RCM15FE
location:
  - Remote
looking:
  - category: UI/UX
    skill: UI Designer (brand building)
  - category: UI/UX
    skill: UX Team manager / Lead
  - category: UI/UX
    skill: UX Researchers (40)
  - category: UI/UX
    skill: UX Designer
  - category: UI/UX
    skill: UX Team Manager / Lead
technologies:
  - Google Docs (Doc, Sheet, Slide, Forms)
  - HackforLA.org guides
partner: Code for America & its Brigades
vertical: Civic Tech Infrastructure
status: Active

```
