### ISSUE TITLE
Project Profile Card Review and Update

### ISSUE THREAD

**Issue by akibrhast** [akibrhast/github-issue-submission-form#44]
<details><summary>For Developer Reference</summary>

```yaml
identification: 288594239 red
title: BallotNav
description: >-
  BallotNav is a tool that aims to help prevent disenfranchisement by providing
  reliable and up to date information on ballot drop off locations across the
  US. While some states have detailed information about ballot drop off
  locations, others leave it up to the local jurisdiction to publish that
  information. In some states, Counties, Towns, Parishes, etc, do not have
  websites, so there is no reliable online source for ballot drop off
  information. BallotNav was created to provide a reliable online resource about
  where to drop your ballot, hours, accessibility, etc. We do this by calling
  each Jurisdictional office provided by the secretary of state and confirming
  locations details.
image: /assets/images/projects/ballot-nav.png
image-hero: /assets/images/projects/ballot-nav-hero.png
alt: Person holding phone with ballot nav website on it.
leadership:
  - name: Karen Coronel
    role: Product Manager
    picture: https://avatars.githubusercontent.com/kcoronel
    links:
      github: https://github.com/kcoronel
      slack: https://hackforla.slack.com/team/U010KUGJATC
  - name: Randall Ellis
    role: Product Manager
    picture: https://avatars.githubusercontent.com/Arjayellis
    links:
      github: https://github.com/Arjayellis
      slack: https://hackforla.slack.com/team/U018TL37XJ6
  - name: Alina Shokina
    role: Product Manager
    picture: https://avatars.githubusercontent.com/allysmatrix
    links:
      github: https://github.com/allysmatrix
      slack: https://hackforla.slack.com/team/U019Y5KEB96
  - name: Jake Mensch
    role: Lead Developer
    picture: https://avatars.githubusercontent.com/jmensch1
    links:
      github: https://github.com/jmensch1
      slack: https://hackforla.slack.com/team/ULJAWB8M8
  - name: Andrew Steman
    role: Lead Developer
    picture: https://avatars.githubusercontent.com/aNullValue
    links:
      github: https://github.com/aNullValue
      slack: https://hackforla.slack.com/team/U01AP5R8U6P
  - name: Seymour Liao
    role: Lead Data Scientist
    picture: https://avatars.githubusercontent.com/Seymour100
    links:
      github: https://github.com/Seymour100
      slack: https://hackforla.slack.com/team/U018XPTSTC6
  - name: Federica Landini
    role: Lead UX Designer
    picture: https://avatars.githubusercontent.com/fedelandini
    links:
      github: https://github.com/fedelandini
      slack: https://hackforla.slack.com/team/U01A9RCMY13
  - name: Irina Rostovtseva
    role: Lead UX Designer
    picture: https://avatars.githubusercontent.com/IrinaRost
    links:
      github: https://github.com/IrinaRost
      slack: https://hackforla.slack.com/team/U01A3MMN59U
links:
  - name: GitHub
    url: https://github.com/hackforla/BallotNav
  - name: Site
    url: http://ballotnav.org
  - name: Slack
    url: https://hackforla.slack.com/archives/C0191KE1XB7
  - name: Readme
    url: https://github.com/hackforla/ballotnav/blob/master/README.md
  - name: Overview
    url: >-
      https://github.com/hackforla/product-management/blob/master/project-one-sheets/BallotNav-Project-One-Sheet.pdf
location:
  - Remote
looking:
  - category: UI/UX
    skill: UX Researcher
  - category: SEO/Marketing
    skill: Marketing, PR & Partnerships
  - category: SEO/Marketing
    skill: Fundraising
  - category: Content
    skill: Translators (Spanish especially)
partner: Code for America, Other Brigades
vertical: Vote / Representation
status: Active

``` 

 </details>
