### ISSUE TITLE
Project Profile Card Review and Update

### ISSUE THREAD

**Issue by akibrhast** [akibrhast/github-issue-submission-form#47]
<details><summary>For Developer Reference</summary>

```yaml

identification: '84370933'
title: 'ArtWatcher '
description: >-
  There are thousands of works of public art scattered around the city.  There
  should be one place to see where they are and how they’re doing. We’re
  building it.
image: /assets/images/projects/adopt-civic-art.jpg
alt: Adopt civic arts 2.0 and 3.0
links:
  - name: GitHub
    url: https://github.com/hackforla/adopt-civic-art
location:
  - Downtown LA
  - Remote
looking:
  - category: Development
    skill: Anyone who wants to write open source automations
partner: County of Los Angeles
status: Active





``` 

 </details>
