### ISSUE TITLE
Project Profile Card Review and Update

### ISSUE THREAD

**Issue by akibrhast** [akibrhast/github-issue-submission-form#50]
<details><summary>For Developer Reference</summary>

```yaml

identification: '216854923'
title: Lucky Parking NEW
description: >-
  Visualization of parking data to assist in understanding of the effects of
  parking policies on a neighborhood by neighborhood basis in the City of Los
  Angeles.
image: /assets/images/projects/lucky-parking.png
image-hero: /assets/images/projects/lucky-parking-hero.png
alt: Lucky Parking Logo
leadership:
  - name: Greg Pawin
    role: Product Owner / Data Science Lead
    picture: https://avatars.githubusercontent.com/gregpawin
    links:
      github: https://github.com/gregpawin
      slack: https://hackforla.slack.com/team/UUEQF3AJG
  - name: Abhinav Bommakanti
    role: Product Manager
    picture: https://avatars.githubusercontent.com/abhib87
    links:
      github: https://github.com/abhib87
      slack: https://hackforla.slack.com/team/U01EW24KL3V
  - name: Matthew Ginther
    role: Full-Stack Developer Lead
    picture: https://avatars.githubusercontent.com/mg78856
    links:
      github: https://github.com/mg78856
      slack: https://hackforla.slack.com/team/U013GNM93U1
  - name: David Lim
    role: Full-Stack Developer
    picture: >-
      https://avatars0.githubusercontent.com/u/38476995?s=400&u=43e9d12bf5a5df1b9347519fc1e4ef3991b9ae13&v=4
    links:
      github: https://github.com/hyomiTheTech
      slack: https://hackforla.slack.com/team/U3MNUEQJ3
  - name: Sam Guan
    role: Full-Stack Developer
    picture: https://avatars.githubusercontent.com/samreality4
    links:
      github: https://github.com/samreality4
      slack: https://hackforla.slack.com/team/U0173AHJ004
links:
  - name: GitHub
    url: https://github.com/hackforla/lucky-parking
  - name: Readme
    url: https://github.com/hackforla/lucky-parking/blob/master/README.md
  - name: Slack
    url: https://hackforla.slack.com/archives/CPFDMSV6V
  - name: Test Site
    url: http://www.luckyparking.info/
location:
  - Remote
looking:
  - category: Development
    skill: Experienced Frontend Software Engineer (Mapbox experience)
  - category: Development
    skill: Experienced Backend Software Engineer
  - category: UI/UX
    skill: Early UI/UX product development
  - category: Data
    skill: Data Analyst/Data Scientist (data cleaning)
technologies:
  - ReactJS
  - PostgreSQL
  - Node.js
  - Mapbox
partner: Department of Neighborhood Empowerment
tools: Jupyter Notebooks, Google Colab, AWS
vertical: Citizen Engagement
status: Active





``` 

 </details>
