### ISSUE TITLE
Project Profile Card Review and Update

### ISSUE THREAD

**Issue by akibrhast** [akibrhast/github-issue-submission-form#9]
```yaml
identification: '336742445'
title: Brigade Organizers Playbook
description: >-
  Each of the 80+ Code for America Brigades is an experiment which generates
  valuable learnings and new effective processes and practices. However,
  Brigades and other civic tech volunteer organizations need not start from
  scratch. This project aims to improve existing structures and create new ones
  that make it easier to share replicable processes and practices so that
  organizers and members can iterate on each others work, improving outcomes for
  the whole network.
image: /assets/images/projects/brigade-organizers-playbook.png
image-hero: /assets/images/projects/brigade-organizers-playbook-hero.png
alt: Brigade Organizer's Playbook Extension Project
leadership:
  - name: Bonnie Wolfe
    role: Agile Mentor & CfA National Advisory Council BOP project Co-Lead
    picture: https://avatars.githubusercontent.com/experimentsinhonesty
    links:
      github: https://github.com/experimentsinhonesty
      slack: https://codeforamerica.slack.com/team/UGREE50MT
  - name: Thad K.
    role: CfA National Advisory Council BOP project Co-Lead
    picture: https://avatars.githubusercontent.com/thadk
    links:
      github: https://github.com/thadk
      slack: https://codeforamerica.slack.com/team/UAU40G31A
  - name: Will Pfeffer
    role: CfA Brigade Network team representative
    picture: https://avatars.githubusercontent.com/willpfeffer
    links:
      github: https://github.com/willpfeffer
      slack: https://codeforamerica.slack.com/team/U014MEJV6KT
  - name: Sam H.
    role: Product Manager
    picture: https://avatars.githubusercontent.com/thesamwong
    links:
      github: https://github.com/thesamwong
      slack: https://codeforamerica.slack.com/team/U019C4LERSM
  - name: Serena Baleja
    role: Product Owner
    picture: https://avatars.githubusercontent.com/Baleja
    links:
      github: https://github.com/Baleja
      slack: https://codeforamerica.slack.com/team/U01FUJ7124S
  - name: Marianne Miranda
    role: UX Research Team Lead
    picture: https://avatars.githubusercontent.com/MarianneAnthonette
    links:
      github: https://github.com/MarianneAnthonette
      slack: https://codeforamerica.slack.com/team/U01ASEG8HK5
  - name: Raquel Nishijima
    role: Communication Designer & UX Researcher
    picture: https://avatars.githubusercontent.com/raquelnish
    links:
      github: https://github.com/raquelnish
      slack: https://codeforamerica.slack.com/team/U01EJ7KMLCV
  - name: Jon Kropko
    role: Data Scientist
    picture: https://avatars.githubusercontent.com/jkropko
    links:
      github: https://github.com/jkropko
      slack: https://codeforamerica.slack.com/team/UL9U380TH
  - name: Tan Zhou
    role: Research Analysis Contributors
    picture: https://avatars.githubusercontent.com/tan-zhou
    links:
      github: https://github.com/tan-zhou
      slack: https://codeforamerica.slack.com/team/UPMSC27G8
  - name: Helen Lin
    role: Research Analysis Contributors
    picture: https://avatars.githubusercontent.com/osnickersnee
    links:
      github: https://github.com/osnickersnee
      slack: https://codeforamerica.slack.com/team/U01B79J9V9B
  - name: Myranda Pierce
    role: Research Analysis Contributors
    picture: https://avatars.githubusercontent.com/myrandi
    links:
      github: https://github.com/myrandi
      slack: https://codeforamerica.slack.com/team/U01E521NT2L
  - name: Reem Mehdoui
    role: Research Analysis Contributors
    picture: https://avatars.githubusercontent.com/reemux
    links:
      github: https://github.com/reemux
      slack: https://codeforamerica.slack.com/team/U01DF6AE5TL
links:
  - name: GitHub
    url: https://github.com/codeforamerica/brigade-playbook
  - name: Slack
    url: https://cfa.slack.com/archives/G0196272BBN
  - name: Wiki
    url: https://github.com/codeforamerica/brigade-playbook/wiki
  - name: Effective Practices
    url: >-
      https://docs.google.com/spreadsheets/d/1N0VSDhYyy5WhX_z18Q0RvLlGO29JGGdMxVsD4X3nFYs/edit#gid=1425278717
location:
  - Remote
technologies:
  - Markdown
partner: >-
  Code for America (CfA), CfA National Advisory Council, Code for Boston, Code
  for Charlottesville
tools: >-
  Zoom, Calendly, Otter.ai, Google Docs (Doc, Sheet, Slide, Forms),
  HackforLA.org guides
status: Active

```

 ## [Preview Changes](#) 

 ## [Make Pull Request](#)
